version: '3.8'

services:
  python-service:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
      - ./output/logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
      - CUDA_VISIBLE_DEVICES=0  # Remove if no GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  # Remove if no GPU
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: sqlite:latest
    volumes:
      - ./database:/data
    environment:
      - SQLITE_DATABASE=/data/ridesecure.db
    restart: unless-stopped